# Generated by Django 5.0 on 2023-12-12 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ex01', '0002_movies_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movies',
            old_name='date',
            new_name='release_date',
        ),
    ]
