# Generated by Django 5.0 on 2023-12-13 00:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ex01', '0004_alter_movies_director_alter_movies_producer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movies',
            name='release_date',
            field=models.DateField(default=datetime.date(2023, 12, 13)),
        ),
    ]
