# Generated by Django 5.0 on 2023-12-12 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ex03', '0003_rename_date_movies_release_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movies',
            name='director',
            field=models.CharField(max_length=32),
        ),
        migrations.AlterField(
            model_name='movies',
            name='producer',
            field=models.CharField(max_length=128),
        ),
    ]
